services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["watchfiles", "--filter", "python", "python /app/src/main.py", "/app/src"]
    env_file:
      - .env
    environment:
      DATABASE_PATH: /data/database.sqlite3
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./data:/data
